language: php
php:
  - 7.0

before_script:
- composer self-update
- composer install --no-interaction --prefer-source
- "mkdir -p ~/.composer"
- cp .travis.composer.config.json ~/.composer/config.json

sudo: false

script: vendor/bin/phpunit