language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev -o

script:
  - vendor/phpspec/phpspec/bin/phpspec run